### ISSUE TITLE
Redesign the View Booking page and add logic to the View Booking page. 

### ISSUE THREAD

**Issue by himanshuyv** [OSDG-IIITH/CabMiloge#2]
## Description

The current view booking page, is just barely functional. There is an option for adding `numbers of hours range`, but that function is yet to be implemented.

## Tasks

- Redesign the view booking page, and the design should match the theme of the website. 
- Add the logic while displaying the booking such that it displays the booking based on the hours entry also, which is coming through the form. Currently, it is based on only the station value.Hours entry is the entry having the number of hours a person wants to look for cabmates prior to his booking time e.g.,  we need to display the booking which are in the range [booking time - number of hours, booking time] for the same station.

![ss](https://github.com/OSDG-IIITH/CabMiloge/assets/127508564/724e123f-bbce-4fb8-a51f-835a3c98a119)

**Comment by gowtham1035** [comment]
I will start working on this
