### ISSUE TITLE
common stying changes over all the projects

### ISSUE THREAD

**Issue by abhiramtilakiiit** [OSDG-IIITH/CabMiloge#24]
## Description

A list of minor frontend changes related to fonts and styling:
- [ ]  If there is any default text, make the font-color grey or some sort of background friendly one.

<img src="https://github.com/user-attachments/assets/ed944443-3938-492a-a151-81305311d5f5" width="480">

- [ ] Font selection in the About Page doesn't sit right with me. Outside of subjective remarks, it would be great if the font-weight of the content was better and fontsize was reasonably smaller. 

- [ ] There are cases where no default text, or default elements were loaded, 
  Eg; in the filters page if there are no results, it would be great if there was some text saying "No rides found".

- [ ] The sidebar has good functionality, but the design has a lot of scope for improvement. It looks really bland right now, especially with the color combination.

<img src="https://github.com/user-attachments/assets/1d12e01b-5970-4493-a94a-27aaadf25431" height="380">

- [ ] In the add new trip page, the input form looks really shabby and unprofessional. The sharp squared selection boxes don't seem to match the rest of the theme, along with the alignment. Other places like "Edit Profile" page and even the auth pages have different and better menus, would be great if those were used here instead.
<img  src="https://github.com/user-attachments/assets/7f56ba69-2023-40e6-8cb4-fd59d16d7f78" height="180">

- [ ] There seem to be two shades of purple in used in the project. The better one in my opinion is darker one

<img src="https://github.com/user-attachments/assets/9042abab-18c5-41e5-8357-53cedac27375" width="480">

Take a look at [osdg website's](osdg.iiit.ac.in), footer. The color fits a lot better there. Here the colors just don't fit with the background. Also better to reduce the empty space (the main website's footer looks a lot better in space management).

## Other info

Even though these design changes are not of functional importance, they help make the project look more appealing.

**Comment by himanshuyv** [comment]
all change done, spread over different commits
