### ISSUE TITLE
Add a dropdown for profile

### ISSUE THREAD

**Issue by himanshuyv** [OSDG-IIITH/CabMiloge#3]
## Description

Right now the header has buttons like `Logout` and `User Name` but the they are not arranged properly.

## Tasks

- Add a dropdown to view profile and create a page having option to edit profile. 
- Add functionality to add profile picture in that.

![ss](https://github.com/OSDG-IIITH/CabMiloge/assets/127508564/978d0b8c-17e3-4c96-bff6-229fc2cf338c)

**Comment by The-Coder-Kishor** [comment]
I am currently working on this issue.
