### ISSUE TITLE
Add functionality to change the type of booking.

### ISSUE THREAD

**Issue by himanshuyv** [OSDG-IIITH/CabMiloge#4]
## Description

Currently, whenever we select a particular type of booking and want to switch to another, we have to reload the page. 

## Tasks

Add some functionality to fix this issue. Recommended methods are:
- Having a drop down menu
- Having a close button or back button of some sort which resets it to default

**Comment by vcnk4v** [comment]
Now we can change the type of booking by clicking on From/To, no need to reload
