### ISSUE TITLE
Integrate CAS into the login page

### ISSUE THREAD

**Issue by abhiramtilakiiit** [OSDG-IIITH/CabMiloge#5]
## Description

The current login page uses regular sign up and login method, and uses SQLite as repo.

## Feature

The task it to get CAS ( Central Authentication Service ), to work with the flask backend and handle the 
`/login` routes in the project.

## Useful Links

Some examples repositories containing example configuration of CAS:
- [casbot](https://github.com/OSDG-IIITH/Discord-CAS): javascript impelementation

- [sacc-webiste](https://github.com/SACC-IIIT-Hyd/SACC_website): python implementation

## Secrets

_will be provided in the session_

**Comment by The-Coder-Kishor** [comment]
I can work on this
